#!/usr/bin/env bash
# loom installer — dependencies, build, and a PATH-visible launcher.
#
#   ./scripts/install.sh
#
# Layout after install (all user-level, no sudo anywhere):
#
#   ~/.loom/bin/loom      the real binary
#   ~/.loom/acp/          claude-code-acp adapter (npm, stable across checkouts)
#   ~/.loom/data/         default data dir (agents, workflows, runs)
#   ~/.local/bin/loom     launcher on PATH: sets LOOM_DATA / LOOM_ACP_CMD
#                         defaults, then execs the binary
#
# A future daemon does NOT need an admin directory: a per-user launchd agent
# (~/Library/LaunchAgents) can point at these absolute paths as-is. Root-owned
# locations only become necessary if loom must run before login or as a system
# service — neither applies to a per-user orchestrator.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOOM_HOME="${LOOM_HOME:-$HOME/.loom}"
BIN_DIR="$LOOM_HOME/bin"
ACP_DIR="$LOOM_HOME/acp"
DATA_DIR="$LOOM_HOME/data"
LAUNCHER_DIR="$HOME/.local/bin"
LAUNCHER="$LAUNCHER_DIR/loom"

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---- 1. dependencies ----

command -v go >/dev/null 2>&1 \
  || die "Go is required (go.mod wants the version pinned there). Install: https://go.dev/dl/ or 'brew install go'"

GO_WANT="$(awk '/^go /{print $2}' "$REPO_ROOT/go.mod")"
info "Go $(go version | awk '{print $3}') found (go.mod wants go${GO_WANT})"

if command -v npm >/dev/null 2>&1; then
  info "installing ACP adapter (claude-code-acp) into $ACP_DIR"
  mkdir -p "$ACP_DIR"
  npm install --prefix "$ACP_DIR" --no-fund --no-audit --loglevel=error @zed-industries/claude-code-acp
else
  warn "npm not found — skipping the ACP adapter. Static workflows degrade to CLI single-shot;"
  warn "dynamic (conversational) workflows will refuse to start. Install Node.js, then re-run."
fi

command -v claude >/dev/null 2>&1 \
  || warn "Claude Code CLI ('claude') not found on PATH — the planner and real runs need it; dry-run works without."

# ---- 2. build ----

info "building loom"
mkdir -p "$BIN_DIR"
(cd "$REPO_ROOT" && go build -o "$BIN_DIR/loom" ./cmd/loom)
info "built $BIN_DIR/loom"

# ---- 3. launcher on PATH ----

mkdir -p "$LAUNCHER_DIR" "$DATA_DIR"

# First install: carry over a repo-local ./data so existing agents, workflows
# and run history don't appear to vanish when 'loom' starts using ~/.loom/data.
if [ -d "$REPO_ROOT/data" ] && [ -z "$(ls -A "$DATA_DIR" 2>/dev/null)" ]; then
  info "migrating existing repo data ($REPO_ROOT/data) → $DATA_DIR"
  cp -R "$REPO_ROOT/data/." "$DATA_DIR/"
fi
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# loom launcher (generated by scripts/install.sh) — pins stable defaults so
# running 'loom' from any directory finds the same data and ACP adapter.
# Your own LOOM_DATA / LOOM_ACP_CMD, or -data / -acp-cmd flags, still win.
export LOOM_DATA="\${LOOM_DATA:-$DATA_DIR}"
if [ -x "$ACP_DIR/node_modules/.bin/claude-code-acp" ]; then
  export LOOM_ACP_CMD="\${LOOM_ACP_CMD:-$ACP_DIR/node_modules/.bin/claude-code-acp}"
fi
exec "$BIN_DIR/loom" "\$@"
EOF
chmod +x "$LAUNCHER"
info "installed launcher at $LAUNCHER (data: $DATA_DIR)"

case ":$PATH:" in
  *":$LAUNCHER_DIR:"*) ;;
  *)
    warn "$LAUNCHER_DIR is not on your PATH. Add this to your shell profile (~/.zshrc):"
    printf '\n    export PATH="$HOME/.local/bin:$PATH"\n\n'
    ;;
esac

info "done. Start loom with:  loom        (http://localhost:7333)"
info "options:  loom -dry-run   |   loom -addr :8080   |   loom -data <dir>"
